.PHONY: run clean

a13:a13.c
	cc -g -ansi -pedantic -Wall a13.c -o a13
	
valgrind:a13
	valgrind ./a13 
	
run:a13
	./a13 ene mene mu und aus bist Du

nemiver:a13
	nemiver ./a13 ene mene mu und aus bist Du


