.PHONY: run clean

a15:a15.c
	cc -g -ansi -pedantic -Wall a15.c -o a15
	
valgrind:a15
	valgrind ./a15
	
run:a15
	./a15 Elend Glogomir Problem unbrauchbar

nemiver:a15
	nemiver ./a15 nazi hitler clemens


